services:
  docs:
    build:
      context: ../
      dockerfile: ./docs/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../docs:/app/docs
      - ../manon:/app/manon
      - ../themes:/app/themes

  visreg-test:
    build:
      context: ./playwright
    command: ["npm", "run", "test"]
    volumes:
      - ./playwright/tests:/app/tests
      - ./playwright/playwright.config.ts:/app/playwright.config.ts
      - ./snapshots:/app/snapshots
      - ./report:/app/report
    depends_on:
      - docs

  visreg-update:
    build:
      context: ./playwright
    command: ["npm", "run", "update"]
    volumes:
      - ./playwright/tests:/app/tests
      - ./playwright/playwright.config.ts:/app/playwright.config.ts
      - ./snapshots:/app/snapshots
      - ./report:/app/report
    depends_on:
      - docs

  visreg-clean:
    build:
      context: ./playwright
    command: ["npm", "run", "clean"]
    volumes:
      - ./playwright/tests:/app/tests
      - ./playwright/playwright.config.ts:/app/playwright.config.ts
      - ./snapshots:/app/snapshots
      - ./report:/app/report
    depends_on:
      - docs
