baseURL = "https://minvws.github.io/nl-rdo-manon/"
title = "Manon Docs"

defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = true

[menu]

[[menu.main]]
name = "Docs"
url = "docs"
weight = 10

[languages]

[languages.nl]
contentDir = "content/nl"
languageName = "Nederlands"
weight = 1

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 2

[markup.goldmark]

[markup.goldmark.parser]
autoHeadingID = false

[markup.goldmark.renderer]
unsafe = true
